services:
  - type: web
    name: vascuscan-backend
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 5005
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
